{{- if and .Values.mediaPvc.enabled (not .Values.mediaPvc.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "recipes-backend.fullname" . }}-media
  labels:
    {{- include "recipes-backend.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.mediaPvc.accessMode }}
  {{- if .Values.mediaPvc.storageClassName }}
  storageClassName: {{ .Values.mediaPvc.storageClassName }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.mediaPvc.size }}
{{- end }}
