apiVersion: v1
kind: Service
metadata:
  name: {{ include "recipes.componentFullname" (dict "component" "scraper" "context" .) }}
  labels:
    {{- include "recipes.componentLabels" (dict "component" "scraper" "context" .) | nindent 4 }}
spec:
  type: {{ .Values.scraper.service.type }}
  ports:
    - port: {{ .Values.scraper.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "recipes.componentSelectorLabels" (dict "component" "scraper" "context" .) | nindent 4 }}
