{{- if .Values.persistence.data.enabled }}
{{- if not .Values.persistence.data.existingClaim }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "recipes-repo.fullname" . }}-data
  labels:
    {{- include "recipes-repo.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- range .Values.persistence.data.accessModes }}
    - {{ . | quote }}
    {{- end }}
  {{- if .Values.persistence.data.storageClass }}
  storageClassName: {{ .Values.persistence.data.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.data.size | quote }}
{{- end }}
{{- end }}
---
{{- if .Values.persistence.media.enabled }}
{{- if not .Values.persistence.media.existingClaim }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "recipes-repo.fullname" . }}-media
  labels:
    {{- include "recipes-repo.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- range .Values.persistence.media.accessModes }}
    - {{ . | quote }}
    {{- end }}
  {{- if .Values.persistence.media.storageClass }}
  storageClassName: {{ .Values.persistence.media.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.media.size | quote }}
{{- end }}
{{- end }}
